* Summer Internship Log

** 7/22/2025
- Practiced Emacs org mode to create a notepage and log for what I've completed.
- Took notes on the propulsion technology of the F450 drone type.
- Took notes on the flight controller and data fetching sensors that are attached to drones.
- Familiarized myself with software such as Ardupilot which assist in automating the drone flight.

** 7/23/2025
- Installed and experimented with firmware such as Ardupilot Mission Planner.
- Picked out the project that I will create for the summer
  - Using the F450 drone underbelly, I began drawing a housing on fusion 360 which will hold a servo that connects to the pixhawk 2.4.8 flight controller.
  - The servo will pull and push a steel rod through the 3D printed hole, allowing for the attachment of a payload.
  - Using mission planner, I will have the drone go to a coordinate using waypoints and release the payload upon arrival.
    - During UAV flight days, someone always has to walk out to retrieve the drone after the flight, so this drone will be able to bring water and other necessary things to the person retrieving the UAV.

** 7/24/2025
- Read up on the 7/24 meeting notes
- Took measurements and finalized 3D model of the servo housing and mounting bracket of the pickup and dropoff mechanism
- Researched proper wiring and use of BEC's (Battery Eliminating Circuits)
- Researched how to properly connect servos to the flight controller, and in turn control the servos with Ardupilot Mission Planner
  
** 7/25/2025
- Presented my drone project to the Zafer UAV team
  - Outlined the process that I would take to fabricate my project
  - Outlined the what my project would be good for
- Researched thrust:weight ratio for optimal flight
  - For my specific project, I will aim for 2:1
  - The thrust from our 4 motors is 2920 grams
    
** 7/29/2025
- Downloaded Slicer software and configured for the K1 MAX 3D printer by Creality
- Began taking apart my assigned F450 drone to analyze the electronics and how to implement my modifications
  - Appended to my notes on the path of electric current in drones
** 7/30/2025
- Figured out the wiring to take power from the ESC and use it to power the servo
- Learned setup for pixhawk 2.4.8 for testing
- Learned about LiPo batteries, and how to charge the 3S variant
  - Checked their charge using a multimeter
- Watched tutorials on how to connect servos to pixhawk 2.4.8
- Reassembled drone
** 7/31/2025
- Decided how to wire the servo and power it using the esc's wiring power and ground cables.
- Watched tutorials on mission planner setup, and how to control servos through the AUX port
- Took off propellers and prepared to wire the servo
** 8/1/2025
- Fitted the wires onto the drone to prepare for the mounting of the servo
  - Stripped 5mm off of the power and ground wires coming off of the ESC
  - Attached two new cables to go from the ESC into AUX out 1, giving power to the servo
- Finalized 3D design of the servos frame, and included the mounting bracket for the servo in the drawing
- Picked out LiPo battery for flight, 3300 mAh, 3S, 40C
** 8/4/2025
- Soldered wires off of the esc, sapping power
- Soldered new wires to the power and ground wires of the servo
- Adjusted 3D drawing to fit the new chosen micro servo

  
