* Summer Internship Log

** 7/22/2025
- Practiced Emacs org mode to create a notepage and log for what I've completed.
- Took notes on the propulsion technology of the F450 drone type.
- Took notes on the flight controller and data fetching sensors that are attached to drones.
- Familiarized myself with software such as Ardupilot which assist in automating the drone flight.

** 7/23/2025
- Installed and experimented with firmware such as Ardupilot Mission Planner.
- Picked out the project that I will create for the summer
  - Using the F450 drone underbelly, I began drawing a housing on fusion 360 which will hold a servo that connects to the pixhawk 2.4.8 flight controller.
  - The servo will pull and push a steel rod through the 3D printed hole, allowing for the attachment of a payload.
  - Using mission planner, I will have the drone go to a coordinate using waypoints and release the payload upon arrival.
    - During UAV flight days, someone always has to walk out to retrieve the drone after the flight, so this drone will be able to bring water and other necessary things to the person retrieving the UAV.

** 7/24/2025
- Read up on todays meeting notes
- Took measurements and finalized 3D model of the servo housing and mounting bracket of the pickup and dropoff mechanism
- Researched proper wiring and use of BEC's (Battery Eliminating Circuits)
- Researched how to properly connect servos to the flight controller, and in turn control the servos with Ardupilot Mission Planner
  
