* Notes For F450 Drone

** Basic Drone Propulsion
- A quadcopter(4 propellers) of the F450 type requires 4 propellers, classified by the 450 mm / 45 cm distance between the center of the drone and the propellers.
- Typically uses 4 brushless dc motors
- ESC is an electronic speed controller and is controlled by the flight controller. The ESC directs the power to the motors and controls their output
- 1x Battery
  - Could use different types, but LiPo has a high power output for the cost

** Flight Controller
- Pixhawk 2.4.8 flight controller is used for our application
- Pixhawk reads sensor data from a GPS module and compass and inputs data into the Ardupilot firmware
- Ardupilot is a firmware that fetches data from GPS modules and other data sensors and compiles them to figure out a track for the drone. The track can also be manipulated by the user.
- Once Ardupilot decides the direction it is going in, the flight controller sends signal to the ESC's, which in turn power the motors.
- Power Module: Although the pixhawk 2.4.8 can function through USB connection, it is necessary to use a power module with ~ 5.3 V of power to power it.
- MicroSD card can also be attached to the flight controller to log data about the flight.
    
** Battery Eliminating Circuits
[[https://www.fs-pcba.com/battery-eliminator-circuit/][FS TECH - BECs]]
- Key Functions
  - Voltage conversion and regulation
  - Space saving and weight reduction
  - Prevents overheating by minimizing heat generation

- Reciever
  - Interprets signals from the transmitter and directs the signal to the ESCs as necessary
- ESC
  - Controls motor speed and direction based on signals from reciever
- Battery
  - Directs power to the ESC's and therefore motors
  - Power from the battery is also transmitted to servos using a BEC
** Path of Current in Drones
- LiPo battery connects to the power module and supplies raw voltage to the power module
  - Red is power, black grounds the current
- Power module has two outputs
  - One goes to the pixhawk 2.4.8 flight controller
    - 1 red cable for power, multiple black ones for grounding and checking the current given to the flight controller
    - Plugged into the power input on the flight controller
    - The flight controller can then distribute this power to things like GPS and telemetry modules
  - The other goes the PDB (Power Distributing Board)
    - There, power is given by one power and one grounding wire, soldered onto the PDB
    - ESC's are connected to the PBD by similar wiring, and take current from it and regulate it before delivering it to the motors
      - However, to be able to do this, they need a signal from the flight controller
      - The pixhawk 2.4.8 does it by delivering control signals from "MAIN OUT" outputs
